14 11 shelters with pending applications
ethanrossblack/adopt-dont-shop-APE pull request #38
Opened 2023-07-17 20:39 UTC by garussell

Completes user story 11
Close #14

2023-07-17 22:05 UTC, ethanrossblack requested changes

2023-07-17 22:05 UTC, ethanrossblack commented on app/models/shelter.rb
> +  end
Add model tests for this class method

2023-07-18 17:05 UTC, ethanrossblack approved these changes
Looks good!

2023-07-18 17:09 UTC, pcbennett108 approved these changes
Looks great!

2023-07-18 17:10 UTC, merged